@startuml
title 空室を確認して部屋を予約する アクティビティ図

start

:利用者がチェックイン日、
チェックアウト日、人数を指定する;

:HRSが条件に合う空室を検索する;

if (空室があるか?) then (はい)
  :HRSが利用可能な部屋一覧を表示する;
  :利用者が予約する部屋を選択する;

  if (部屋が選択されたか?) then (はい)
    :HRSが予約を作成する;
    :HRSが予約番号を発行する;
    :HRSが予約番号を利用者に通知する;
  else (いいえ)
    :HRSは予約を作成しない;
  endif

else (いいえ)
  :HRSが空室なしを通知する;
endif

stop

@enduml
