@startuml
package ユーザインタフェース {
class チェックアウト画面 <<boundary>>{
  +部屋番号または予約番号を入力する() : void
  +宿泊料を表示する() : void
  +完了メッセージを表示する() : void
}
class 予約画面 <<boundary>>{
  +宿泊日を入力する() : void
  +空室一覧を表示する() : void
  +予約番号を表示する() : void
}
class チェックイン画面 <<boundary>>{
  +予約番号を入力する() : void
  +予約内容を表示する() : void
  +部屋番号を表示する() : void
}
}

package アプリケーション {
class 予約処理 <<control>>{
  +空室を検索する() : void
  +予約を作成する() : void
  +予約番号を返す() : void
}
class チェックアウト処理 <<control>>{
  +宿泊情報を確認する() : void
  +宿泊料を計算する() : void
  +支払いを記録する() : void
  +チェックアウト状態に更新する() : void
  +部屋を空ける() : void
  +チェックアウトを完了する() : void
}
class チェックイン処理 <<control>>{
  +予約情報を確認する() : void
  +部屋を割り当てる() : void
  +支払い情報を作成する() : void
  +部屋番号を返す() : void
}
class 予約管理 <<control>>{
  +予約番号を発行する() : void
  +予約を登録する() : void
  +予約を検索する() : void
  +予約状態を更新する() : void
}
class 支払い管理 <<control>>{
  +宿泊料を計算する() : void
  +支払い情報を作成する() : void
  +支払い状態を更新する() : void
  +支払い済みを確認する() : void
}
class 部屋管理 <<control>>{
  +空席数を取得する() : void
  +空室を検索する() : void
  +部屋を割り当てる() : void
  +部屋状態を更新する() : void
}
}

package ドメイン {
class 予約 <<entity>>{
  -予約番号 : int
  -チェックイン日 : int
  -チェックアウト日 : int
  -人数 : int
  -予約状態 : int
}
class 部屋 <<entity>>{
  -部屋番号 : int
  -部屋種別 : int
  -宿泊料金 : int
  -部屋状態 : int
}
class ホテル受付係 <<entity>>{
  -氏名 : int
}
class 利用者 <<entity>>{
  -氏名 : int
  -連絡先 : int
}
class 空席数 {
  -日付 : int
  -空席数 : int
}
class 宿泊 <<entity>>{
  -宿泊開始日 : int
  -宿泊終了日 : int
  -宿泊状態 : int
}
class 宿泊料 <<entity>>{
  -金額 : int
}
class 支払い <<entity>>{
  -支払い日 : int
  -支払い金額 : int
  -支払い方法 : int
  -支払い状態 : int
}
}

予約画面 "1" o--> "1" 予約処理
チェックイン画面 "1" o--> "1" チェックイン処理
チェックアウト画面 "1" o--> "1" チェックアウト処理
予約処理 "1" --> "1" 予約管理
予約処理 "1" --> "1" 部屋管理
チェックイン処理 "1" --> "1" 予約管理
チェックイン処理 "1" --> "1" 部屋管理
チェックイン処理 "1" --> "1" 支払い管理
チェックアウト処理 "1" --> "1" 部屋管理
チェックアウト処理 "1" --> "1" 支払い管理
予約管理 "1" --> "0..*" 予約
部屋管理 "1" --> "0..*" 部屋
部屋管理 "1" --> "0..*" 空席数
支払い管理 "1" --> "0..*" 支払い
支払い管理 "1" --> "0..*" 宿泊料
利用者 "1" -- "0..*" 予約
ホテル受付係 "1" -- "0..*" 予約
予約 -- 部屋
予約 "0..1" -- "0..1" 宿泊
宿泊 "1" -- "1" 部屋
宿泊 "1" -- "1" 宿泊料
宿泊料 "1" -- "0..1" 支払い
部屋 "0..*" -- "0..*" 空席数
@enduml
